###############################################
## This dockerfile is used to just bring up
## the services needed to have a bestbets api.
## (Without data)
version: '3'
services:
  elasticsearch:
    build: elasticsearch
    networks:
      - overlay
  cancergov:
    image: httpd:2.4-alpine
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./cancergov/apache-conf/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./cancergov/apache-conf/conf/extra:/usr/local/apache2/conf/extra
      - ./_shared/certs:/etc/apache2/ssl
    networks:
      overlay:
        aliases:
          - cancergov
          - preview-cancergov
  loader:
    build: 
      context: ./
      dockerfile: loader/Dockerfile
    networks:
      - overlay

#  bestbets-api:
#    build: bestbets-api
#    networks:
#      - overlay
#    ports:
#      - "5000:5000"
#    depends_on:
#      - "cancergov"
#      - "elasticsearch"

networks:
  overlay: