version: '3'
services:
  elasticsearch:
    build: elasticsearch
    networks:
      - overlay
  cancergov:
    build: cancergov
    volumes:
      - cancergov/htdocs:/usr/local/apache2/htdocs/
      - cancergov/apache-conf/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - cancergov/apache-conf/conf/extra:/usr/local/apache2/conf/extra
      - _shared/certs:/etc/apache2/ssl
    networks:
      - overlay:
          aliases:
            - preview-cancergov
  bestbets-api:
    build: bestbets-api
    networks:
      - overlay
  tester:
    build: tester
    networks:
      - overlay
networks:
  overlay: